#! /bin/sh

#
# Apps to start on load
#
killall -q picom
picom &
killall -q sxhkd
sxhkd &
killall -q polybar
polybar full &

xsetroot -cursor_name left_ptr

bspc monitor LVDS-1 -d 1 2 3 4 5 6 7
#bspc monitor VGA1 -d 6 7 8 9 10

# Border gaps,width, and padding
bspc config border_width         2
bspc config window_gap           5
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
 
bspc config top_padding          35
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

# Mouse actions
bspc config pointer_action1 move
#bspc config pointer_action3 resize_corners

# Focus on pointer
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
