#! /bin/sh

#
# Apps to start on load
#
killall -q picom
picom &
killall -q sxhkd
sxhkd &
killall -q polybar
polybar full &
killall -q flameshot
flameshot &
killall -q dunst
dunst &

nitrogen --restore &

xsetroot -cursor_name left_ptr &

bspc monitor -d  󰖟   󰋋

# Border gaps,width, and padding
bspc config border_width         2
bspc config window_gap           10
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
 
bspc config top_padding          30
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

bspc config normal_border_color "#7ccdfd"
bspc config active_border_color "#7ccdfd"
bspc config focused_border_color "#f5748c"
bspc config presel-feedback_colour "#fc9d63"

# Mouse actions
bspc config pointer_action1 move
#bspc config pointer_action3 resize_corners

# Focus on pointer
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
