general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Iosevka Nerd Font" }
bold = { family = "Iosevka Nerd Font" }
italic = { family = "Iosevka Nerd Font" }
size = 14

[window]
padding.x = 5
padding.y = 5
decorations = "None"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
