import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[shell]
program = "/bin/zsh"
args = ['-c', 'tmux']

[font]
size = 11.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[env]
TERM = "xterm-256color"
